package gengo

import "math/rand/v2"

// This file implements the shared WordsPT closed-class infrastructure and the
// closed-class selectors ArticlePT, PrepositionPT, ConjunctionPT, PronounPT, and
// InterjectionPT, plus their mirrored *Generator methods.
//
// Closed classes differ fundamentally from the open classes (noun, adjective,
// verb, adverb). An open class is GENERATED by the three-layer pipeline into a
// plausible invented word; a closed class is SELECTED, unchanged, from a curated,
// exhaustive list of real pt-PT single words. There is no morphology, no
// accentuation layer, and no length concept: every member is already a correct,
// lowercase, accented pt-PT word, and the selector's only job is to pick one
// uniformly at random. See specification/wordspt-closed-classes.md and
// specification/wordspt.md ("Closed class"; "Length applies only to open
// classes").
//
// Membership criteria (specification/wordspt-closed-classes.md, "General rules
// for closed classes"): every member is a REAL pt-PT word (never invented), a
// SINGLE word (no multi-word locutions), spelled under the Acordo Ortográfico da
// Língua Portuguesa in its European-Portuguese form, output in LOWERCASE with
// correct graphic accents, and the list is exhaustive for its class.
//
// Selection is a single slice index (pickClosedClass). The returned string shares
// the embedded list's backing array, so the pick itself performs no allocation;
// the length concept is ignored entirely, so the selectors take no length
// parameter.
//
// Randomness surfaces. The package-level ArticlePT/PrepositionPT/ConjunctionPT
// draw from the global, automatically seeded math/rand/v2 source (through the
// shared wordsPTGlobalRand wrapper defined in wordspt_noun.go); the (*Generator)
// methods draw from the generator's own seeded source. Both call the single
// shared pickClosedClass with an injectable *rand.Rand, so there is no
// duplication and a seeded Generator is fully reproducible.
//
// Sources for the curated lists: Cunha, C. & Cintra, L., "Nova Gramática do
// Português Contemporâneo" (the essential/simple prepositions; the definite,
// indefinite, and contracted articles; the single-word coordinating and
// subordinating conjunctions; the personal, possessive, demonstrative,
// indefinite, relative, and interrogative pronoun paradigms, including the
// archaic-but-real vós forms; the representative interjections); Acordo
// Ortográfico da Língua Portuguesa (graphic accent placement, including the
// grave accent that marks the crasis contractions à and às, and the pt-PT
// spellings such as "connosco" over the Brazilian "conosco").

// ---------------------------------------------------------------------------
// Shared closed-class selector
// ---------------------------------------------------------------------------

// pickClosedClass returns a member of a curated closed-class list, chosen
// uniformly at random from r. It is the single selection engine shared by every
// closed-class selector (the package-level functions and the *Generator methods),
// so a seeded Generator is fully reproducible and there is no per-class
// duplication.
//
// The selection is one slice index: the returned string shares members' backing
// array, so the pick allocates nothing. Length is ignored, in line with the
// closed-class rule that length applies only to open classes, so no length
// parameter is taken.
//
// members must be non-empty; every curated list in this package is a non-empty
// compile-time literal, so the index is always valid.
func pickClosedClass(r *rand.Rand, members []string) string {
	return members[r.IntN(len(members))]
}

// ---------------------------------------------------------------------------
// Curated closed-class lists (embedded, exhaustive, pt-PT)
// ---------------------------------------------------------------------------

// articlesPT is the exhaustive curated list of real pt-PT single-word articles:
// the definite articles, the indefinite articles, and the single-word
// contractions of a preposition with an article. The contractions "à" and "às"
// carry the grave accent, which marks the crasis of the preposition "a" with the
// article "a" or "as". Every member is a single word, lowercase, and correctly
// accented under the Acordo Ortográfico. The order is documentary only; selection
// is uniform and index-independent.
var articlesPT = []string{
	// Definite: o/a/os/as.
	"o", "a", "os", "as",
	// Indefinite: um/uma/uns/umas.
	"um", "uma", "uns", "umas",
	// Contractions of "de" with the definite article: de + o/a/os/as.
	"do", "da", "dos", "das",
	// Contractions of "em" with the definite article: em + o/a/os/as.
	"no", "na", "nos", "nas",
	// Contractions of "em" with the indefinite article: em + um/uma/uns/umas.
	"num", "numa", "nuns", "numas",
	// Contractions of "de" with the indefinite article: de + um/uma/uns/umas.
	"dum", "duma", "duns", "dumas",
	// Contractions of "por" (archaic "per") with the definite article: per + o/a/os/as.
	"pelo", "pela", "pelos", "pelas",
	// Contractions of "a" with the definite article; "à"/"às" carry the crasis grave accent.
	"ao", "aos", "à", "às",
}

// prepositionsPT is the exhaustive curated list of the essential (simple) pt-PT
// prepositions, per specification/wordspt-closed-classes.md. Only essential
// prepositions are included; accidental prepositions (words borrowed from other
// classes, such as "conforme" or "segundo") and prepositional locutions (such as
// "de acordo com") are excluded. Every member is lowercase and correctly
// accented; "após", "até", and "trás" carry the acute accent.
var prepositionsPT = []string{
	"a", "ante", "após", "até", "com", "contra", "de", "desde", "em",
	"entre", "para", "perante", "por", "sem", "sob", "sobre", "trás",
}

// conjunctionsPT is the exhaustive curated list of real pt-PT single-word
// conjunctions, coordinating and subordinating. Only single words are included;
// conjunctional locutions (such as "à medida que") are excluded. Several members
// ("conforme", "consoante", "segundo") also belong to other closed classes; the
// closed-class lists are independent, so a word may legitimately appear in more
// than one. Every member is lowercase and correctly accented; "porém" carries the
// acute accent.
var conjunctionsPT = []string{
	// Coordinating.
	"e", "nem", "mas", "porém", "todavia", "contudo", "entretanto",
	"ou", "ora", "logo", "portanto", "pois", "assim", "senão", "outrossim",
	// Subordinating.
	"que", "se", "porque", "porquanto", "conquanto", "embora", "como",
	"quando", "enquanto", "mal", "caso", "conforme", "consoante", "segundo", "salvo",
}

// pronounsPT is the exhaustive curated list of real pt-PT single-word pronouns,
// spanning every subtype: personal (subject, atonic oblique, and tonic oblique),
// possessive, demonstrative, indefinite, relative, and interrogative. All
// gender/number forms of the variable pronouns are included, as are the
// archaic-but-real second-person-plural forms related to "vós" ("vós", "vos",
// "vosso"/"vossa"/"vossos"/"vossas", "convosco"). The pt-PT spelling "connosco"
// is used (not the Brazilian "conosco").
//
// A pronoun may belong to more than one subtype (for example "que" and "quem"
// are both relative and interrogative; the "quanto" series is indefinite,
// relative, and interrogative; the eight subject forms double as tonic-oblique
// forms). Each such member is listed exactly once,
// under its first subtype, so the list is duplicate-free. Some members also spell
// words of other closed classes ("o"/"a"/"os"/"as" are articles; "se" is a
// conjunction); the closed-class lists are independent, so this overlap is
// expected. Every member is lowercase and correctly accented; the order is
// documentary only, since selection is uniform and index-independent.
var pronounsPT = []string{
	// Personal — subject (nominative), including the archaic-but-real "vós".
	"eu", "tu", "ele", "ela", "nós", "vós", "eles", "elas", //nolint:misspell // real pt-PT pronouns; US misspell mistakes the plural form for the English "eels"
	// Personal — oblique atonic (clitic, unstressed object forms).
	"me", "te", "se", "o", "a", "lhe", "nos", "vos", "os", "as", "lhes",
	// Personal — oblique tonic (stressed, preposition-governed), plus the
	// "com"+pronoun contractions. The eight subject forms above (including "vós")
	// also serve as tonic obliques and are listed once, there.
	"mim", "ti", "si", "comigo", "contigo", "consigo", "connosco", "convosco",
	// Possessive: all gender/number forms of the five series.
	"meu", "minha", "meus", "minhas",
	"teu", "tua", "teus", "tuas",
	"seu", "sua", "seus", "suas",
	"nosso", "nossa", "nossos", "nossas",
	"vosso", "vossa", "vossos", "vossas",
	// Demonstrative: the variable series with their gender/number forms, the
	// invariable neuters "isto"/"isso"/"aquilo", and the "tal"/"tais" and
	// "semelhante"/"semelhantes" pairs.
	"este", "esta", "estes", "estas", "isto",
	"esse", "essa", "esses", "essas", "isso",
	"aquele", "aquela", "aqueles", "aquelas", "aquilo",
	"mesmo", "mesma", "mesmos", "mesmas",
	"próprio", "própria", "próprios", "próprias",
	"tal", "tais",
	"semelhante", "semelhantes",
	// Indefinite: the variable series with their gender/number forms, the
	// "qualquer"/"quaisquer" pair, and the invariable indefinites. The "quanto"
	// series is also relative and interrogative; it is listed once, here.
	"algum", "alguma", "alguns", "algumas",
	"nenhum", "nenhuma", "nenhuns", "nenhumas",
	"todo", "toda", "todos", "todas",
	"outro", "outra", "outros", "outras",
	"muito", "muita", "muitos", "muitas",
	"pouco", "pouca", "poucos", "poucas",
	"tanto", "tanta", "tantos", "tantas",
	"quanto", "quanta", "quantos", "quantas",
	"vário", "vária", "vários", "várias",
	"certo", "certa", "certos", "certas",
	"qualquer", "quaisquer",
	"alguém", "ninguém", "tudo", "nada", "algo", "cada", "outrem",
	// Relative: "que"/"quem", "qual"/"quais", and the "cujo" series. "que",
	// "quem", "qual", "quais" also serve as interrogatives and are listed once,
	// here.
	"que", "quem", "qual", "quais",
	"cujo", "cuja", "cujos", "cujas",
	// Interrogative: every interrogative pronoun is also relative or indefinite
	// and is already listed above — "quem", "que", "qual"/"quais" (relative) and
	// the "quanto"/"quanta"/"quantos"/"quantas" series (indefinite) — so this
	// subtype contributes no member of its own. The interrogative/relative words
	// "onde", "quando", "como", and "porquê" are adverbs, not pronouns (Cunha &
	// Cintra), and are therefore excluded from this list.
}

// interjectionsPT is a curated, representative list of real pt-PT single-word
// interjections — the diffuse, largely onomatopoeic class of exclamations
// (emotive, appellative, and volitive). Interjectional locutions (for example
// "ai de mim") are excluded. Every member is a single word, lowercase, and
// correctly accented ("ó", "olá", "olé", "hã", "oxalá" carry graphic accents);
// the order is documentary only, since selection is uniform and
// index-independent.
var interjectionsPT = []string{
	"ah", "oh", "ó", "olá", "oi", "ui", "ai", "eh", "hã", "hum", "uf", "ufa",
	"oxalá", "tomara", "viva", "bravo", "olé", "chiu", "psiu", "bolas", "caramba",
	"credo", "coitado", "adeus", "alto", "avante", "arre", "upa", "eia", "salve",
	"ora", "apre",
}

// ---------------------------------------------------------------------------
// Public API: package-level functions
// ---------------------------------------------------------------------------

// ArticlePT returns a real European-Portuguese (pt-PT) article, selected
// uniformly at random from the curated, exhaustive list of single-word articles
// (definite, indefinite, and single-word preposition+article contractions such as
// "do", "no", "pelo", "à"). The result is a real, lowercase, correctly accented
// pt-PT word, never invented; the length concept does not apply to closed
// classes, so ArticlePT takes no length option.
//
// ArticlePT draws from the global, automatically seeded math/rand/v2 source and is
// safe for concurrent use by multiple goroutines. For reproducible output, use a
// seeded Generator ([New] or [NewSource]) and its ArticlePT method.
func ArticlePT() string {
	return pickClosedClass(wordsPTGlobalRand, articlesPT)
}

// PrepositionPT returns a real pt-PT preposition, selected uniformly at random
// from the curated, exhaustive list of essential (simple) prepositions (for
// example "a", "de", "para", "após", "sobre"). The result is a real, lowercase,
// correctly accented pt-PT word; prepositional locutions are excluded and the
// length concept does not apply, so PrepositionPT takes no length option.
//
// PrepositionPT draws from the global, automatically seeded math/rand/v2 source
// and is safe for concurrent use by multiple goroutines. For reproducible output,
// use a seeded Generator ([New] or [NewSource]) and its PrepositionPT method.
func PrepositionPT() string {
	return pickClosedClass(wordsPTGlobalRand, prepositionsPT)
}

// ConjunctionPT returns a real pt-PT conjunction, selected uniformly at random
// from the curated, exhaustive list of single-word coordinating and subordinating
// conjunctions (for example "e", "mas", "porém", "porque", "embora"). The result
// is a real, lowercase, correctly accented pt-PT word; conjunctional locutions are
// excluded and the length concept does not apply, so ConjunctionPT takes no length
// option.
//
// ConjunctionPT draws from the global, automatically seeded math/rand/v2 source
// and is safe for concurrent use by multiple goroutines. For reproducible output,
// use a seeded Generator ([New] or [NewSource]) and its ConjunctionPT method.
func ConjunctionPT() string {
	return pickClosedClass(wordsPTGlobalRand, conjunctionsPT)
}

// PronounPT returns a real pt-PT pronoun, selected uniformly at random from the
// curated, exhaustive list that spans every subtype: personal (subject, atonic
// oblique, and tonic oblique, including the archaic-but-real "vós" forms such as
// "vós", "convosco", and "vosso"), possessive, demonstrative, indefinite,
// relative, and interrogative (for example "eu", "lhe", "consigo", "minhas",
// "aquilo", "nenhuma", "cujo", "quem"). The result is a real, lowercase,
// correctly accented pt-PT word; the length concept does not apply to closed
// classes, so PronounPT takes no length option.
//
// PronounPT draws from the global, automatically seeded math/rand/v2 source and is
// safe for concurrent use by multiple goroutines. For reproducible output, use a
// seeded Generator ([New] or [NewSource]) and its PronounPT method.
func PronounPT() string {
	return pickClosedClass(wordsPTGlobalRand, pronounsPT)
}

// InterjectionPT returns a real pt-PT interjection, selected uniformly at random
// from the curated, representative list of single-word interjections (for example
// "ah", "olá", "oxalá", "caramba", "psiu", "arre"). The result is a real,
// lowercase, correctly accented pt-PT word; interjectional locutions are excluded
// and the length concept does not apply, so InterjectionPT takes no length option.
//
// InterjectionPT draws from the global, automatically seeded math/rand/v2 source
// and is safe for concurrent use by multiple goroutines. For reproducible output,
// use a seeded Generator ([New] or [NewSource]) and its InterjectionPT method.
func InterjectionPT() string {
	return pickClosedClass(wordsPTGlobalRand, interjectionsPT)
}

// ---------------------------------------------------------------------------
// Public API: *Generator methods
// ---------------------------------------------------------------------------

// ArticlePT is the seeded-generator equivalent of [ArticlePT]. A Generator created
// with the same seed produces the same sequence of articles.
func (g *Generator) ArticlePT() string {
	return pickClosedClass(g.r, articlesPT)
}

// PrepositionPT is the seeded-generator equivalent of [PrepositionPT]. A Generator
// created with the same seed produces the same sequence of prepositions.
func (g *Generator) PrepositionPT() string {
	return pickClosedClass(g.r, prepositionsPT)
}

// ConjunctionPT is the seeded-generator equivalent of [ConjunctionPT]. A Generator
// created with the same seed produces the same sequence of conjunctions.
func (g *Generator) ConjunctionPT() string {
	return pickClosedClass(g.r, conjunctionsPT)
}

// PronounPT is the seeded-generator equivalent of [PronounPT]. A Generator created
// with the same seed produces the same sequence of pronouns.
func (g *Generator) PronounPT() string {
	return pickClosedClass(g.r, pronounsPT)
}

// InterjectionPT is the seeded-generator equivalent of [InterjectionPT]. A
// Generator created with the same seed produces the same sequence of
// interjections.
func (g *Generator) InterjectionPT() string {
	return pickClosedClass(g.r, interjectionsPT)
}
