//go:build ignore

// This program generates wordspt_skew_table.go, the integer threshold table that
// skewedCharTarget (wordspt_inflection.go) uses in place of the closed-form
// inverse CDF of the truncated geometric word-length draw. Run it through
// `go generate` from the module root; it uses only the standard library.
//
// For every span s in [1, skewTableMaxSpan] and every offset k in [1, s], the
// table holds the smallest 32-bit draw x for which the closed-form offset
// (skewOffsetFormula below, a verbatim copy of the package function of the same
// name) is at least k. The offset is non-decreasing in x, so the offset of any
// draw equals the number of thresholds of its span that are less than or equal
// to the draw. The package tests prove, against the package's own formula, that
// every emitted threshold is exact.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"math"
	"os"
)

// outputFile is the generated file, written in the current directory (the module
// root when run through go generate).
const outputFile = "wordspt_skew_table.go"

// skewTableMaxSpan is the largest span the table covers. It equals the widest
// character window of charRangeOf (1..30) minus one, the largest span that
// skewedCharTarget receives.
const skewTableMaxSpan = 29

// lengthSkewDecay mirrors the package constant of the same name.
const lengthSkewDecay = 0.78

// lengthSkewLnDecay mirrors the package variable of the same name.
var lengthSkewLnDecay = math.Log(lengthSkewDecay)

// skewOffsetFormula mirrors the package function of the same name: the offset of
// the truncated geometric inverse CDF for the raw 32-bit draw x and window span.
func skewOffsetFormula(span int, x uint32) int {
	u := (float64(x) + 0.5) / 4294967296.0
	denom := 1 - math.Pow(lengthSkewDecay, float64(span+1))
	offset := int(math.Ceil(math.Log(1-float64(u*denom))/lengthSkewLnDecay)) - 1
	if offset < 0 {
		offset = 0
	} else if offset > span {
		offset = span
	}
	return offset
}

// threshold returns the smallest x in [0, 2^32) with skewOffsetFormula(span, x)
// >= k, found by bisection over the non-decreasing offset. It fails when no draw
// reaches k, because the table stores only 32-bit thresholds.
func threshold(span, k int) uint32 {
	if skewOffsetFormula(span, math.MaxUint32) < k {
		log.Fatalf("span %d: offset %d is unreachable by any 32-bit draw", span, k)
	}
	lo, hi := uint64(0), uint64(math.MaxUint32)
	for lo < hi {
		mid := lo + (hi-lo)/2
		if skewOffsetFormula(span, uint32(mid)) >= k {
			hi = mid
		} else {
			lo = mid + 1
		}
	}
	return uint32(lo)
}

func main() {
	var b bytes.Buffer
	b.WriteString(`// Code generated by go run wordspt_skew_gen.go; DO NOT EDIT.

package gengo

// skewTableMaxSpan is the largest window span covered by [skewThresholds]. It
// equals the widest character window of [charRangeOf] (1..30) minus one, so
// every span that [skewedCharTarget] receives from the length machinery is
// covered.
`)
	fmt.Fprintf(&b, "const skewTableMaxSpan = %d\n\n", skewTableMaxSpan)
	b.WriteString(`// skewThresholds holds, for every span s in [1, skewTableMaxSpan], the s
// thresholds of that span, stored contiguously from index s*(s-1)/2. Threshold
// k-1 of span s is the smallest 32-bit draw x for which [skewOffsetFormula]
// returns at least k, so the offset of a draw is the number of thresholds of its
// span that are less than or equal to it.
var skewThresholds = [...]uint32{
`)
	for s := 1; s <= skewTableMaxSpan; s++ {
		fmt.Fprintf(&b, "// span %d\n", s)
		for k := 1; k <= s; k++ {
			fmt.Fprintf(&b, "%d,", threshold(s, k))
			if k%6 == 0 || k == s {
				b.WriteByte('\n')
			} else {
				b.WriteByte(' ')
			}
		}
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(outputFile, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", outputFile, err)
	}
}
