package gengo

import "math/rand/v2"

// This file implements the shared WordsPT closed-class infrastructure and the
// first three closed-class selectors: ArticlePT, PrepositionPT, and
// ConjunctionPT, plus their mirrored *Generator methods.
//
// Closed classes differ fundamentally from the open classes (noun, adjective,
// verb, adverb). An open class is GENERATED by the three-layer pipeline into a
// plausible invented word; a closed class is SELECTED, unchanged, from a curated,
// exhaustive list of real pt-PT single words. There is no morphology, no
// accentuation layer, and no length concept: every member is already a correct,
// lowercase, accented pt-PT word, and the selector's only job is to pick one
// uniformly at random. See specification/wordspt-closed-classes.md and
// specification/wordspt.md ("Closed class"; "Length applies only to open
// classes").
//
// Membership criteria (specification/wordspt-closed-classes.md, "General rules
// for closed classes"): every member is a REAL pt-PT word (never invented), a
// SINGLE word (no multi-word locutions), spelled under the Acordo Ortográfico da
// Língua Portuguesa in its European-Portuguese form, output in LOWERCASE with
// correct graphic accents, and the list is exhaustive for its class.
//
// Selection is a single slice index (pickClosedClass). The returned string shares
// the embedded list's backing array, so the pick itself performs no allocation;
// the length concept is ignored entirely, so the selectors take no length
// parameter.
//
// Randomness surfaces. The package-level ArticlePT/PrepositionPT/ConjunctionPT
// draw from the global, automatically seeded math/rand/v2 source (through the
// shared wordsPTGlobalRand wrapper defined in wordspt_noun.go); the (*Generator)
// methods draw from the generator's own seeded source. Both call the single
// shared pickClosedClass with an injectable *rand.Rand, so there is no
// duplication and a seeded Generator is fully reproducible.
//
// Sources for the curated lists: Cunha, C. & Cintra, L., "Nova Gramática do
// Português Contemporâneo" (the essential/simple prepositions; the definite,
// indefinite, and contracted articles; the single-word coordinating and
// subordinating conjunctions); Acordo Ortográfico da Língua Portuguesa (graphic
// accent placement, including the grave accent that marks the crasis
// contractions à and às).

// ---------------------------------------------------------------------------
// Shared closed-class selector
// ---------------------------------------------------------------------------

// pickClosedClass returns a member of a curated closed-class list, chosen
// uniformly at random from r. It is the single selection engine shared by every
// closed-class selector (the package-level functions and the *Generator methods),
// so a seeded Generator is fully reproducible and there is no per-class
// duplication.
//
// The selection is one slice index: the returned string shares members' backing
// array, so the pick allocates nothing. Length is ignored, in line with the
// closed-class rule that length applies only to open classes, so no length
// parameter is taken.
//
// members must be non-empty; every curated list in this package is a non-empty
// compile-time literal, so the index is always valid.
func pickClosedClass(r *rand.Rand, members []string) string {
	return members[r.IntN(len(members))]
}

// ---------------------------------------------------------------------------
// Curated closed-class lists (embedded, exhaustive, pt-PT)
// ---------------------------------------------------------------------------

// articlesPT is the exhaustive curated list of real pt-PT single-word articles:
// the definite articles, the indefinite articles, and the single-word
// contractions of a preposition with an article. The contractions "à" and "às"
// carry the grave accent, which marks the crasis of the preposition "a" with the
// article "a" or "as". Every member is a single word, lowercase, and correctly
// accented under the Acordo Ortográfico. The order is documentary only; selection
// is uniform and index-independent.
var articlesPT = []string{
	// Definite: o/a/os/as.
	"o", "a", "os", "as",
	// Indefinite: um/uma/uns/umas.
	"um", "uma", "uns", "umas",
	// Contractions of "de" with the definite article: de + o/a/os/as.
	"do", "da", "dos", "das",
	// Contractions of "em" with the definite article: em + o/a/os/as.
	"no", "na", "nos", "nas",
	// Contractions of "em" with the indefinite article: em + um/uma/uns/umas.
	"num", "numa", "nuns", "numas",
	// Contractions of "de" with the indefinite article: de + um/uma/uns/umas.
	"dum", "duma", "duns", "dumas",
	// Contractions of "por" (archaic "per") with the definite article: per + o/a/os/as.
	"pelo", "pela", "pelos", "pelas",
	// Contractions of "a" with the definite article; "à"/"às" carry the crasis grave accent.
	"ao", "aos", "à", "às",
}

// prepositionsPT is the exhaustive curated list of the essential (simple) pt-PT
// prepositions, per specification/wordspt-closed-classes.md. Only essential
// prepositions are included; accidental prepositions (words borrowed from other
// classes, such as "conforme" or "segundo") and prepositional locutions (such as
// "de acordo com") are excluded. Every member is lowercase and correctly
// accented; "após", "até", and "trás" carry the acute accent.
var prepositionsPT = []string{
	"a", "ante", "após", "até", "com", "contra", "de", "desde", "em",
	"entre", "para", "perante", "por", "sem", "sob", "sobre", "trás",
}

// conjunctionsPT is the exhaustive curated list of real pt-PT single-word
// conjunctions, coordinating and subordinating. Only single words are included;
// conjunctional locutions (such as "à medida que") are excluded. Several members
// ("conforme", "consoante", "segundo") also belong to other closed classes; the
// closed-class lists are independent, so a word may legitimately appear in more
// than one. Every member is lowercase and correctly accented; "porém" carries the
// acute accent.
var conjunctionsPT = []string{
	// Coordinating.
	"e", "nem", "mas", "porém", "todavia", "contudo", "entretanto",
	"ou", "ora", "logo", "portanto", "pois", "assim", "senão", "outrossim",
	// Subordinating.
	"que", "se", "porque", "porquanto", "conquanto", "embora", "como",
	"quando", "enquanto", "mal", "caso", "conforme", "consoante", "segundo", "salvo",
}

// ---------------------------------------------------------------------------
// Public API: package-level functions
// ---------------------------------------------------------------------------

// ArticlePT returns a real European-Portuguese (pt-PT) article, selected
// uniformly at random from the curated, exhaustive list of single-word articles
// (definite, indefinite, and single-word preposition+article contractions such as
// "do", "no", "pelo", "à"). The result is a real, lowercase, correctly accented
// pt-PT word, never invented; the length concept does not apply to closed
// classes, so ArticlePT takes no length option.
//
// ArticlePT draws from the global, automatically seeded math/rand/v2 source and is
// safe for concurrent use by multiple goroutines. For reproducible output, use a
// seeded Generator ([New] or [NewSource]) and its ArticlePT method.
func ArticlePT() string {
	return pickClosedClass(wordsPTGlobalRand, articlesPT)
}

// PrepositionPT returns a real pt-PT preposition, selected uniformly at random
// from the curated, exhaustive list of essential (simple) prepositions (for
// example "a", "de", "para", "após", "sobre"). The result is a real, lowercase,
// correctly accented pt-PT word; prepositional locutions are excluded and the
// length concept does not apply, so PrepositionPT takes no length option.
//
// PrepositionPT draws from the global, automatically seeded math/rand/v2 source
// and is safe for concurrent use by multiple goroutines. For reproducible output,
// use a seeded Generator ([New] or [NewSource]) and its PrepositionPT method.
func PrepositionPT() string {
	return pickClosedClass(wordsPTGlobalRand, prepositionsPT)
}

// ConjunctionPT returns a real pt-PT conjunction, selected uniformly at random
// from the curated, exhaustive list of single-word coordinating and subordinating
// conjunctions (for example "e", "mas", "porém", "porque", "embora"). The result
// is a real, lowercase, correctly accented pt-PT word; conjunctional locutions are
// excluded and the length concept does not apply, so ConjunctionPT takes no length
// option.
//
// ConjunctionPT draws from the global, automatically seeded math/rand/v2 source
// and is safe for concurrent use by multiple goroutines. For reproducible output,
// use a seeded Generator ([New] or [NewSource]) and its ConjunctionPT method.
func ConjunctionPT() string {
	return pickClosedClass(wordsPTGlobalRand, conjunctionsPT)
}

// ---------------------------------------------------------------------------
// Public API: *Generator methods
// ---------------------------------------------------------------------------

// ArticlePT is the seeded-generator equivalent of [ArticlePT]. A Generator created
// with the same seed produces the same sequence of articles.
func (g *Generator) ArticlePT() string {
	return pickClosedClass(g.r, articlesPT)
}

// PrepositionPT is the seeded-generator equivalent of [PrepositionPT]. A Generator
// created with the same seed produces the same sequence of prepositions.
func (g *Generator) PrepositionPT() string {
	return pickClosedClass(g.r, prepositionsPT)
}

// ConjunctionPT is the seeded-generator equivalent of [ConjunctionPT]. A Generator
// created with the same seed produces the same sequence of conjunctions.
func (g *Generator) ConjunctionPT() string {
	return pickClosedClass(g.r, conjunctionsPT)
}
